{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name | replace "_" "-" }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $name | replace "_" "-" }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
{{- if $svc.extraPorts }}
{{- range $p := $svc.extraPorts }}
    - port: {{ $p }}
      targetPort: {{ $p }}
{{- end }}
{{- end }}
---
{{- end }}
