apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-gateway
  namespace: kd39
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-gateway
  template:
    metadata:
      labels:
        app: access-gateway
    spec:
      containers:
        - name: access-gateway
          image: kd39/access-gateway:latest
          args: ["/app/config/access_gateway.yaml"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: kd39-config
---
apiVersion: v1
kind: Service
metadata:
  name: access-gateway
  namespace: kd39
spec:
  selector:
    app: access-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
